import { lazy } from 'react'
/* eslint-disable */
export const operationViewMap = {
  'product-storage': {
    //create: lazy(() => import('../components/DisplayPanel/views/product-storage/Create')),
    create: null as any,
    //edit: lazy(() => import('../components/DisplayPanel/views/product-storage/Edit')),
    edit: null as any,
    //delete: lazy(() => import('../components/DisplayPanel/views/product-storage/Delete')),
    delete: null as any,
    //view: lazy(() => import('../components/DisplayPanel/views/product-storage/View')),
    view: null as any,
  },
  'production-materials': {
    //create: lazy(() => import('../components/DisplayPanel/views/production-materials/Create')),
    create: null as any,
    //edit: lazy(() => import('../components/DisplayPanel/views/production-materials/Edit')),
    edit: null as any,
    //delete: lazy(() => import('../components/DisplayPanel/views/production-materials/Delete')),
    delete: null as any,
    //view: lazy(() => import('../components/DisplayPanel/views/production-materials/View')),
    view: null as any,
  },
  'production-reports': {
    //create: lazy(() => import('../components/DisplayPanel/views/production-reports/Create')),
    create: null as any,
    //edit: lazy(() => import('../components/DisplayPanel/views/production-reports/Edit')),
    edit: null as any,
    //delete: lazy(() => import('../components/DisplayPanel/views/production-reports/Delete')),
    delete: null as any,
    //view: lazy(() => import('../components/DisplayPanel/views/production-reports/View')),
    view: null as any,
  },
  'products': {
    //create: lazy(() => import('../components/DisplayPanel/views/products/Create')),
    create: null as any,
    //edit: lazy(() => import('../components/DisplayPanel/views/products/Edit')),
    edit: null as any,
    //delete: lazy(() => import('../components/DisplayPanel/views/products/Delete')),
    delete: null as any,
    //view: lazy(() => import('../components/DisplayPanel/views/products/View')),
    view: null as any,
  },
  'raw-materials': {
    //create: lazy(() => import('../components/DisplayPanel/views/raw-materials/Create')),
    create: null as any,
    //edit: lazy(() => import('../components/DisplayPanel/views/raw-materials/Edit')),
    edit: null as any,
    //delete: lazy(() => import('../components/DisplayPanel/views/raw-materials/Delete')),
    delete: null as any,
    //view: lazy(() => import('../components/DisplayPanel/views/raw-materials/View')),
    view: null as any,
  },
  'raw-storage': {
    //create: lazy(() => import('../components/DisplayPanel/views/raw-storage/Create')),
    create: null as any,
    //edit: lazy(() => import('../components/DisplayPanel/views/raw-storage/Edit')),
    edit: null as any,
    //delete: lazy(() => import('../components/DisplayPanel/views/raw-storage/Delete')),
    delete: null as any,
    //view: lazy(() => import('../components/DisplayPanel/views/raw-storage/View')),
    view: null as any,
  },
  'staff': {
    //create: lazy(() => import('../components/DisplayPanel/views/staff/Create')),
    create: null as any,
    //edit: lazy(() => import('../components/DisplayPanel/views/staff/Edit')),
    edit: null as any,
    //delete: lazy(() => import('../components/DisplayPanel/views/staff/Delete')),
    delete: null as any,
    view: lazy(() => import('../components/DisplayPanel/views/staff/ViewStaff.tsx')),
  }
} as const

